Repository pythonpune/linkstatus, pull requests merged in 2019-12, with the labels that each got.

#18 Added contribution guidelines
  CONTRIBUTING.md
  README.md
Labels: documentation, pyconfhyd

#20 [RFR] Introduce tests for linkstatus
  .github/workflows/main.yml
  dev-requirements.txt
  linkstatus/linkstatus.py
  tests/conftest.py
  tests/data.yaml
  tests/data/markdown_file.md
  tests/data/recursive/recursive_text_file.txt
  tests/data/text_file
  tests/test_methods.py
Labels: enhancement

#22 test linkstatus command
  tests/test_linkstatus.py
Labels: enhancement

#21 [RFR] check for linux, win, mac
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: enhancement

#23 Added test for parse_file, link_status checks
  linkstatus/linkstatus.py
  tests/conftest.py
  tests/data.yaml
  tests/data/markdown_file.md
  tests/test_methods.py
Labels: enhancement, tests
