Repository pythonpune/linkstatus, pull requests merged in 2020-02, with the labels that each got.

#24 Added nox support. Fixes #10
  .github/workflows/main.yml
  .gitignore
  noxfile.py
Labels: enhancement

#27 RFR: Enhancement in nox
  .github/workflows/main.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  README.md
  dev-requirements.txt
  noxfile.py
Labels: documentation, enhancement

#29 Update pre-commit hooks to latest
  .pre-commit-config.yaml
Labels: enhancement

#28 RFR: No more full summary if link count zero
  linkstatus/linkstatus.py
  tests/test_linkstatus.py
Labels: bug
